application: scaffold
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: scaffold.wsgi.application
  login: admin

- url: /.*
  script: scaffold.wsgi.application


skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*